# Generated by Django 5.1.4 on 2025-03-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='username',
        ),
    ]
