# Generated by Django 5.1.4 on 2025-03-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_faculty_options_alter_faculty_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
