# Generated by Django 5.1.7 on 2025-03-14 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end',
        ),
    ]
