# Generated by Django 5.1.7 on 2025-03-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='leave_balance',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
