# Generated by Django 5.1.7 on 2025-03-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_leave_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='department',
        ),
    ]
